server:
  port: 9091
spring:
  batch:
    job:
      enabled: false
  datasource:
    url: jdbc:h2:file:~/xxx12356;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  boot:
    admin:
      client:
        url: http://localhost:9090
        username: admin
        password: admin
  application:
    name: Barch
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always